### PR TITLE
Feat/styles

### PR DESCRIPTION
**Pull request by gauravfs-14**
- [x] Change Blue Theme to Yellow
- [x] Change Container Margins for mobile devices
- [x] Changed Research Page to Projects & Grants page
- [x] Modify tabs setting in Projects & Grants page
- [x] Add search and sort functionality in Grants page
- [x] Lazy Load components in Projects and Grants page
- [x] Added #navigation to the tabs
- [x] Changed badges style
- [x] Change the text selection accent color globally
- [x] Homepage sections background change

### CODE REVIEW

**Comment by Xatta-Trone** [comment]
image


make the names dark gray

**Comment by Xatta-Trone** [comment]
@gauravfs-14

**Comment by Xatta-Trone** [comment]
@gauravfs-14 

image



make it paginated and add a search bar.

**Comment by Xatta-Trone** [comment]
@gauravfs-14 

image


for the media tag use some other grayish color... but not the same color as other label.

**Comment by Xatta-Trone** [comment]
@gauravfs-14 

image


button should be filled, add resume/pdf icon 


image


button should be same as in the home page

**Comment by Xatta-Trone** [comment]
@gauravfs-14 

image


can you make it dark bg like the footer..... 
image


the h4, make the font bigger (3xl).

**Comment by Xatta-Trone** [comment]
@gauravfs-14 
image


tags should be same color as project and grants page.

**Comment by Xatta-Trone** [comment]
image


remove the description, make all the cards same height.

**Comment by Xatta-Trone** [comment]
@gauravfs-14 

image


please show the date time into a human readable format (in the current timezone)

**Comment by gauravfs-14** [comment]
#### Updated Code Task List

- [x] Teams Page Card Heading Style
- [x] News And Update Page Pagination, Search, Debounce
- [x] Talks and Media Page card badge style
- [x] About Page buttons style and icons
- [x] Homepage Footer/Contact section styles
- [x] Course Card Badge styles
- [x] Homepage project swiper styles

**Comment by Xatta-Trone** [comment]
@gauravfs-14 

image


Please add the keyword, page number in the url to preserve the state like other pages.

**Comment by Xatta-Trone** [comment]
image


Order the book -> Order Here

@gauravfs-14

**Comment by Xatta-Trone** [comment]
@gauravfs-14 
image



add white border top in the footer section.

**Comment by Xatta-Trone** [comment]
@gauravfs-14 

image


label padding: 2px 8px to make it look better.

**Comment by Xatta-Trone** [comment]
@gauravfs-14 
image


please check all buttons hover, visited state. On hover the text color should be white and background should be primary color (yellow)

**Comment by Xatta-Trone** [comment]
@gauravfs-14 

image


for swastika barua -> remove the twitter link 
for monzurul islam -> orcid id https://orcid.org/0009-0007-3670-6100

**Comment by Xatta-Trone** [comment]
image


ahmed hossain -> ( Fall 2024 -> (Fall 2024 -> remove the space before fall

**Comment by Xatta-Trone** [comment]
That's all from me for now.

**Comment by gauravfs-14** [comment]
#### New Task List

- [x] Homepage All news open in same tab with next/link
- [x] Small screen homepage hero section separator triangle
- [x] Team members data update (ahmed hossain -> Fall 2024, Polock -> starting year Fall 2024, for swastika barua -> remove the twitter link, for monzurul islam -> orcid id
- [x] Pagination buttons hover animation
- [x] All cards label paddings
- [x] Footer border top white
- [x] Contact Us Section colors
- [x] Button change: Order the book -> Order Here
- [x] News page: keyword, page number in the url to preserve the state like other pages while search

**Comment by gauravfs-14** [comment]
Fixed Build Error: Suspense Error

**Comment by Xatta-Trone** [comment]
> @gauravfs-14
> 
> image
> 
> Label padding: 2px 8px to make it look better. Please change it for all labels on all pages.

padding top-bottom 2px left right 8px @gauravfs-14

**Comment by Xatta-Trone** [comment]
@gauravfs-14  for the next stage 

image


when I am changing the page the page should scroll up...not stay in the current position.

**Comment by Xatta-Trone** [comment]
@gauravfs-14  I am merging this PR, please take care of the pagination scroll issue in a new PR

**Pull request merged**
