### PR TITLE
[fix]: pagination scroll to top

### PR DESCRIPTION
**Pull request by gauravfs-14**

### CODE REVIEW

**Comment by gauravfs-14** [comment]
Fixed Pagination Issue

**Comment by Xatta-Trone** [comment]
1. make the scroll smooth.... currently it is just jumping to the top. Not a good UX.
2. I think there is a issue with the animation in this section, currently it is just flipping, please fix it. 

image

**Comment by Xatta-Trone** [comment]
@gauravfs-14

**Comment by gauravfs-14** [comment]
> 1. make the scroll smooth.... currently it is just jumping to the top. Not a good UX.
> 2. I think there is a issue with the animation in this section, currently it is just flipping, please fix it.
> 
> image

Fixed

**Pull request merged**
